### ISSUE TITLE
Provide builds for M series Apple Silicon Macs (darwin_arm64)

### ISSUE THREAD

**Issue by timfallmk** [iovisor/kubectl-trace#178]
Currently attempted installs on M series Macs will result in an error (the one from `krew` for example:
```
krew install trace
Updated the local copy of plugin index.
Installing plugin: trace
W1217 16:47:48.709643   54251 install.go:164] failed to install plugin "trace": plugin "trace" does not offer installation for this platform
F1217 16:47:48.709695   54251 root.go:79] failed to install some plugins: [trace]: plugin "trace" does not offer installation for this platform
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xac
k8s.io/klog/v2.(*loggingT).output(0x102fcf6c0, 0x3, {0x0, 0x0}, 0x140001840e0, {0x102cee3e3, 0x7}, 0x4f, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x588
k8s.io/klog/v2.(*loggingT).printDepth(0x102fcf6c0, 0x3, {0x0, 0x0}, {0x0, 0x0}, 0x1, {0x1400066ec00, 0x1, 0x1})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:733 +0x1ac
k8s.io/klog/v2.(*loggingT).print(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:715
k8s.io/klog/v2.Fatal(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1489
sigs.k8s.io/krew/cmd/krew/cmd.Execute()
	/private/tmp/krew-20211024-22302-196yo0l/cmd/krew/cmd/root.go:79 +0x228
main.main()
	/private/tmp/krew-20211024-22302-196yo0l/cmd/krew/main.go:25 +0x3c

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x102fcf6c0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x70
created by k8s.io/klog/v2.init.0
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0x150
```
This is due to the absence of `darwin_arm64` compiled binaries. It should be possible to add this to the cross compilation list for release fairly easily.

**Comment by lobshunter** [comment]
May I ask for a new release? The latest version is [v0.1.2](https://github.com/iovisor/kubectl-trace/releases/tag/v0.1.2) which doesn't carry the enhancement PR.
